spring.datasource.url=jdbc:postgresql://dpg-d7lqup9o3t8c73epv2q0-a:5432/brightminds_db_srj3?sslmode=require
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
